model:
  fusion: txt2img
  K: 1
  prompt_template: ["a photo of x x", "a photo of x x", "a photo of x x"]
  ctx_init: ["a photo of ", "a photo of ", "a photo of "]
  clip_model: "ViT-L/14"
  res_w: 0.8
  SA_K: 1
  width_img: 1024
  width_txt: 768
  num_query_token: 16
  dataset_path: 
  patch_size: 14
  image_size: 224
  adapter_dim: 64
  adapter_dropout: 0.1
  beta: 1
  alpha: 1
train:
  dataset: cgqa
  dataset_path: 
  lr: 0.00005
  lr_sgd: 0.001
  attr_dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 32
  gradient_accumulation_steps: 1
  seed: 0
  epochs: 20
  epoch_start: 0  
  save_model: True
  save_path: 
  best_model_metric: best_loss     #best_unseen  best_seen AUC best_loss best_hm
  load_model:   # False or model path
  att_obj_w: 0.01
  sp_w: 0.1

test:
  dataset_path: 
  eval_batch_size: 16
  open_world: False
  topk: 1
  text_encoder_batch_size: 36
  # threshold: 0.4
  threshold_trials: 50
  bias: 0.001