model:
  prompt_template: ["a photo of x x", "a photo of x", "a photo of x"]
  ctx_init: ["a photo of ", "a photo of ", "a photo of "]
  clip_model: "ViT-L/14"
  adapter_dim: 64
  adapter_dropout: 0.1
  # branch
  save_every_n: 1
  best_model_metric: best_loss
  alpha: 0.7
  beta: 0.3
  train_only: true

train:
  dataset: ut-zappos
  # dataset_path: 
  optimizer: Adam
  scheduler: StepLR
  step_size: 5
  gamma: 0.5
  lr: 0.0005     # 0.00025
  attr_dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 16 # 64
  gradient_accumulation_steps: 1
  # seed: 
  epochs: 20
  epoch_start: 0
  save_path: 
  val_metric: AUC
  save_final_model: True
  load_model: 
  dataset_path:  



test:
  eval_batch_size: 8
  open_world: False
  # load_model: 
  topk: 1
  text_encoder_batch_size: 1024
  # threshold: 0.4
  threshold_trials: 50
  bias: 0.001
  text_first: False
  enabled: True